CREATE SCHEMA IF NOT EXISTS user (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NIT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);